/** @type {{ [key: string]: any }} */

const images = {
  "manzana.png": require("../assets/images/manzana.png"),
  "banana.png": require("../assets/images/banana.png"),
  "naranja.png": require("../assets/images/naranja.png"),
  "pera.png": require("../assets/images/pera.png"),
  "uvas.png": require("../assets/images/uvas.png"),
  "piña.png": require("../assets/images/piña.png"),
  "mango.png": require("../assets/images/mango.png"),
  "frutillas.png": require("../assets/images/frutillas.png"),
  "kiwi.png": require("../assets/images/kiwi.png"),
  "cerezas.png": require("../assets/images/cerezas.png"),
  "melocoton.png": require("../assets/images/melocoton.png"),
  "sandia.png": require("../assets/images/sandia.png"),
  "limon.png": require("../assets/images/limon.png"),
  "maracuya.png": require("../assets/images/maracuya.png"),
  "coco.png": require("../assets/images/coco.png"),
  "granada.png": require("../assets/images/granada.png"),
  "lima.png": require("../assets/images/lima.png"),
  "arandanos.png": require("../assets/images/arandanos.png"),
  "frambuesas.png": require("../assets/images/frambuesas.png"),
  "melon.png": require("../assets/images/melon.png"),
  "higo.png": require("../assets/images/higo.png"),
  "moras.png": require("../assets/images/moras.png"),
  "uvasVerdes.png": require("../assets/images/uvasVerdes.png"),
  "cebolla.png": require("../assets/images/cebolla.png"),
  "tomate.png": require("../assets/images/tomate.png"),
  "lechuga.png": require("../assets/images/lechuga.png"),
  "zanahoria.png": require("../assets/images/zanahoria.png"),
  "brocoli.png": require("../assets/images/broccoli.png"),
  "espinaca.png": require("../assets/images/espinaca.png"),
  "pepino.png": require("../assets/images/pepino.png"),
  "berenjena.png": require("../assets/images/berenjena.png"),
  "apio.png": require("../assets/images/apio.png"),
  "remolacha.png": require("../assets/images/remolacha.png"),
  "nabo.png": require("../assets/images/nabo.png"),
  "rabanitos.png": require("../assets/images/rabanito.png"),
  "aguacate.png": require("../assets/images/ahuacate.png"),
  "boniatoZanahoria.png": require("../assets/images/boniatoZanahoria.png"),
  "boniato.png": require("../assets/images/boniato.png"),
  "choclo.png": require("../assets/images/choclo.png"),
  "cebollaVerdeo.png": require("../assets/images/cebollaVerdeo.png"),
  "cibullete.png": require("../assets/images/cibullette.png"),
  "kabutia.png": require("../assets/images/kabutia.png"),
  "lechugaRoble": require("../assets/images/lechugaRoble.png"),
  "morron.png": require("../assets/images/morron.png"),
  "MorronVerde.png": require("../assets/images/MorronVerde.png"),
  "papaBlanca.png": require("../assets/images/papaBlanca.png"),
  "papaRosada.png": require("../assets/images/papaRosada.png"),
  "puerro.png": require("../assets/images/puerro.png"),
  "rucula.png": require("../assets/images/rucula.png"),
  "suchinni.png": require("../assets/images/suchinni.png"),
  "zapallito.png": require("../assets/images/zapallito.png"),
  "zapallo.png": require("../assets/images/zapallo.png"),
};

export default images;
